personne_contact_comme_concept_lié_à_programme
data-players/Opaline pull request #18
Opened 2022-02-28 18:51 UTC by VincentFarcy

2022-02-28 21:49 UTC, simonLouvet commented on middleware/public/ontology.ttl
> +:affiliatedBy rdf:type owl:ObjectProperty ;
pourquoi recréer des concepts qui existent déjà dan PAIR?

2022-02-28 22:09 UTC, VincentFarcy commented on middleware/public/ontology.ttl
> +:affiliatedBy rdf:type owl:ObjectProperty ;
c'est corrigé

2022-03-07 13:43 UTC, VincentFarcy commented
@simonLouvet J'ai retiré organization du state comme discuté

2022-03-11 09:09 UTC, simonLouvet requested changes

2022-03-11 09:09 UTC, simonLouvet commented on middleware/public/ontology.ttl
>  :programOfferedBy rdf:type owl:ObjectProperty ;
enlever le type de sujet du prédicat

2022-03-11 21:55 UTC, VincentFarcy commented on middleware/public/ontology.ttl
>  :programOfferedBy rdf:type owl:ObjectProperty ;
c'est fait

2022-03-12 18:31 UTC, simonLouvet approved these changes

2022-03-12 18:32 UTC, simonLouvet commented
@VincentFarcy peux tu corriger le conflit stp. je merge dans la foulée

2022-03-12 20:09 UTC, VincentFarcy commented
@simonLouvet  conflit corrigé

2022-03-14 14:49 UTC, simonLouvet approved these changes

2022-03-14 14:49 UTC, merged