16 lieu de formation comme concept lie a programme
data-players/Opaline pull request #19
Opened 2022-03-01 15:27 UTC by VincentFarcy

2022-03-07 13:43 UTC, VincentFarcy commented
@simonLouvet J'ai retiré organization du state comme discuté

2022-03-11 09:07 UTC, simonLouvet requested changes

2022-03-11 09:07 UTC, simonLouvet commented on middleware/public/ontology.ttl
> +:trainingSiteOfferedBy rdf:type owl:ObjectProperty ;
enlever le type de sujet du prédicat

2022-03-11 21:54 UTC, VincentFarcy commented on middleware/public/ontology.ttl
> +:trainingSiteOfferedBy rdf:type owl:ObjectProperty ;
c'est fait

2022-03-11 21:54 UTC, VincentFarcy commented on middleware/public/ontology.ttl
> +:trainingSiteOffers rdf:type owl:ObjectProperty ;
c'est fait

2022-03-12 18:32 UTC, simonLouvet approved these changes

2022-03-12 18:32 UTC, merged